[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
randomness_beacon = "98BYuJuJu6QQxcYyfZCfpMVNqYKoigc14XG1tesULSVN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace -- --nocapture"
