[build]
rustflags = [
  "--check-cfg=cfg(feature, values(\"anchor-debug\", \"custom-heap\", \"custom-panic\", \"no-log-ix-name\"))",
  "--check-cfg=cfg(target_os, values(\"solana\"))",
]

[env]
SBF_OUT_DIR = { value = "target/deploy", relative = true }