use std::{fs, path::Path};

use anyhow::{Context, Result};
use ark_bn254::{g1::G1Affine, g2::G2Affine, Bn254, Fq};
use ark_ff::{BigInteger, PrimeField};
use ark_groth16::VerifyingKey;
use ark_serialize::CanonicalSerialize;

pub fn export_ark_vk_for_solana(vk: &VerifyingKey<Bn254>, out: &Path) -> Result<()> {
    let mut compressed = Vec::new();
    vk.serialize_compressed(&mut compressed)
        .context("failed to serialize verifying key")?;

    let alpha = g1_to_bytes(&vk.alpha_g1);
    let beta = g2_to_bytes(&vk.beta_g2);
    let gamma = g2_to_bytes(&vk.gamma_g2);
    let delta = g2_to_bytes(&vk.delta_g2);
    let ic: Vec<[u8; 64]> = vk.gamma_abc_g1.iter().map(g1_to_bytes).collect();
    let ic_len = ic.len();

    let source = format!(
        r#"// Auto-generated by `cargo run -p setup -- local-random`.
// Local random setup is development-only. Production deployments should import
// ceremony output from snarkjs and independently verify the generated constants.

use groth16_solana::groth16::Groth16Verifyingkey;

pub const PUBLIC_INPUT_COUNT: usize = 2;
pub const ARKWORKS_VERIFYING_KEY_COMPRESSED: &[u8] = &{:?};
pub const VK_IC: [[u8; 64]; {}] = {:?};

pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {{
    nr_pubinputs: PUBLIC_INPUT_COUNT,
    vk_alpha_g1: {:?},
    vk_beta_g2: {:?},
    vk_gamme_g2: {:?},
    vk_delta_g2: {:?},
    vk_ic: &VK_IC,
}};
"#,
        compressed, ic_len, ic, alpha, beta, gamma, delta
    );

    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(out, source).with_context(|| format!("failed to write {}", out.display()))
}

fn fq_to_be_bytes(value: &Fq) -> [u8; 32] {
    let bytes = (*value).into_bigint().to_bytes_be();
    let mut out = [0u8; 32];
    let start = out.len().saturating_sub(bytes.len());
    out[start..].copy_from_slice(&bytes);
    out
}

fn g1_to_bytes(point: &G1Affine) -> [u8; 64] {
    let x = fq_to_be_bytes(&point.x);
    let y = fq_to_be_bytes(&point.y);
    let mut out = [0u8; 64];
    out[..32].copy_from_slice(&x);
    out[32..].copy_from_slice(&y);
    out
}

fn g2_to_bytes(point: &G2Affine) -> [u8; 128] {
    let x0 = fq_to_be_bytes(&point.x.c0);
    let x1 = fq_to_be_bytes(&point.x.c1);
    let y0 = fq_to_be_bytes(&point.y.c0);
    let y1 = fq_to_be_bytes(&point.y.c1);
    let mut out = [0u8; 128];
    out[..32].copy_from_slice(&x1);
    out[32..64].copy_from_slice(&x0);
    out[64..96].copy_from_slice(&y1);
    out[96..].copy_from_slice(&y0);
    out
}

pub fn export_snarkjs_vk_json_for_solana(vk_json: &serde_json::Value, out: &Path) -> Result<()> {
    let source = format!(
        r###"// Auto-generated by `cargo run -p setup -- import-ceremony`.
// This source preserves the snarkjs verification key JSON that should be
// converted into groth16_solana::groth16::Groth16Verifyingkey constants before
// deploying to mainnet.

pub const PUBLIC_INPUT_COUNT: usize = 2;
pub const SNARKJS_VERIFYING_KEY_JSON: &str = r##"{}"##;
"###,
        serde_json::to_string_pretty(vk_json).context("failed to format verification key JSON")?
    );

    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    }
    fs::write(out, source).with_context(|| format!("failed to write {}", out.display()))
}
